In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_wine

In [2]:
data = load_wine()

In [3]:
X = data.data

In [4]:
y = data.target

### Bagging

In [5]:
from sklearn.ensemble import BaggingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [6]:
cart = LogisticRegression()

In [7]:
model = BaggingClassifier(cart)

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size =0.3)

In [9]:
model.fit(X_train,Y_train)

BaggingClassifier(base_estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
         bootstrap=True, bootstrap_features=False, max_features=1.0,
         max_samples=1.0, n_estimators=10, n_jobs=1, oob_score=False,
         random_state=None, verbose=0, warm_start=False)

In [10]:
pre = model.predict(X_test)

In [11]:
from  sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [12]:
print(classification_report(pre,Y_test))

             precision    recall  f1-score   support

          0       0.94      0.94      0.94        17
          1       0.92      0.92      0.92        26
          2       0.91      0.91      0.91        11

avg / total       0.93      0.93      0.93        54



In [13]:
print(confusion_matrix(pre,Y_test))

[[16  1  0]
 [ 1 24  1]
 [ 0  1 10]]


In [14]:
print(accuracy_score(pre,Y_test))

0.9259259259259259


#### Random Forest Classifier

In [15]:
from sklearn.ensemble import RandomForestClassifier

In [16]:
model2 = RandomForestClassifier(n_estimators=100,n_jobs=2,random_state=7)

In [17]:
model2.fit(X_train,Y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=2,
            oob_score=False, random_state=7, verbose=0, warm_start=False)

In [18]:
pre2 = model2.predict(X_test)

In [19]:
print(classification_report(pre2,Y_test))

             precision    recall  f1-score   support

          0       1.00      0.94      0.97        18
          1       0.96      1.00      0.98        25
          2       1.00      1.00      1.00        11

avg / total       0.98      0.98      0.98        54



In [20]:
print(confusion_matrix(pre2,Y_test))

[[17  1  0]
 [ 0 25  0]
 [ 0  0 11]]


In [21]:
print(accuracy_score(pre2,Y_test))

0.9814814814814815


### Boosting

#### Gradient Boosting Classifier

In [22]:
from sklearn.ensemble import GradientBoostingClassifier

In [23]:
model3 = GradientBoostingClassifier(n_estimators=100,random_state=7)

In [24]:
model3.fit(X_train,Y_train)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=100,
              presort='auto', random_state=7, subsample=1.0, verbose=0,
              warm_start=False)

In [25]:
pre3 = model3.predict(X_test)

In [26]:
print(classification_report(pre3,Y_test))

             precision    recall  f1-score   support

          0       1.00      0.94      0.97        18
          1       0.92      1.00      0.96        24
          2       1.00      0.92      0.96        12

avg / total       0.97      0.96      0.96        54



In [27]:
print(confusion_matrix(pre3,Y_test))

[[17  1  0]
 [ 0 24  0]
 [ 0  1 11]]


In [28]:
print(accuracy_score(pre3,Y_test))

0.9629629629629629


### Voting

In [29]:
from sklearn.ensemble import VotingClassifier

In [30]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB

In [31]:
estimater = []
model4 = DecisionTreeClassifier()
estimater.append(("Decision tree",model4))
model5 = LogisticRegression()
estimater.append(("Logistic",model5))
model6 = SVC(kernel="rbf")
estimater.append(("SVm",model6))

In [32]:
classify = VotingClassifier(estimater)

In [33]:
classify.fit(X_train,Y_train)

VotingClassifier(estimators=[('Decision tree', DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fr...,
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False))],
         flatten_transform=None, n_jobs=1, voting='hard', weights=None)

In [34]:
pre4 = classify.predict(X_test)

C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [35]:
print(classification_report(pre4,Y_test))

             precision    recall  f1-score   support

          0       0.94      1.00      0.97        16
          1       0.96      0.86      0.91        29
          2       0.73      0.89      0.80         9

avg / total       0.92      0.91      0.91        54



In [36]:
print(confusion_matrix(pre4,Y_test))

[[16  0  0]
 [ 1 25  3]
 [ 0  1  8]]


In [37]:
print(accuracy_score(pre4,Y_test)*100)

90.74074074074075
