In [2]:
import pandas as pd 
import numpy as np
from sklearn.datasets import load_digits
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [3]:
digits = load_digits()

In [4]:
X = digits.data
Y = digits.target

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size =0.3,random_state = 7)

## Support Vector Machine

In [6]:
from sklearn.svm import SVC

### Linear kernel

In [8]:
linear = SVC(kernel ="linear")

In [9]:
linear.fit(X_train,Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [10]:
pre_linear = linear.predict(X_test)

#### Classification report

In [11]:
print(classification_report(pre_linear,Y_test))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        61
          1       0.93      0.94      0.94        54
          2       1.00      0.98      0.99        54
          3       0.96      0.96      0.96        52
          4       0.98      0.98      0.98        58
          5       1.00      0.89      0.94        54
          6       1.00      1.00      1.00        48
          7       0.96      0.96      0.96        49
          8       0.87      0.90      0.89        60
          9       0.91      0.98      0.94        50

avg / total       0.96      0.96      0.96       540



#### Confusion matrix

In [12]:
print(confusion_matrix(pre_linear,Y_test))

[[61  0  0  0  0  0  0  0  0  0]
 [ 0 51  0  0  0  0  0  0  3  0]
 [ 0  0 53  0  0  0  0  0  1  0]
 [ 0  0  0 50  0  0  0  0  1  1]
 [ 0  0  0  0 57  0  0  0  1  0]
 [ 0  0  0  1  0 48  0  1  1  3]
 [ 0  0  0  0  0  0 48  0  0  0]
 [ 0  0  0  0  1  0  0 47  1  0]
 [ 0  4  0  0  0  0  0  1 54  1]
 [ 0  0  0  1  0  0  0  0  0 49]]


#### Accuracy score

In [13]:
print(accuracy_score(pre_linear, Y_test))

0.9592592592592593


### Polynomial

In [14]:
poly = SVC(kernel = "poly",degree  =8)

In [16]:
poly.fit(X_train,Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=8, gamma='auto', kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [17]:
pre_poly = poly.predict(X_test)

#### Classification Report

In [19]:
print(classification_report(pre_poly,Y_test))

             precision    recall  f1-score   support

          0       0.97      1.00      0.98        59
          1       0.96      0.88      0.92        60
          2       1.00      0.98      0.99        54
          3       1.00      0.96      0.98        54
          4       0.98      0.97      0.97        59
          5       0.98      0.92      0.95        51
          6       0.98      1.00      0.99        47
          7       0.98      0.98      0.98        49
          8       0.81      0.94      0.87        53
          9       0.94      0.94      0.94        54

avg / total       0.96      0.96      0.96       540



#### Confusion Matrix

In [20]:
print(confusion_matrix(pre_poly,Y_test))

[[59  0  0  0  0  0  0  0  0  0]
 [ 0 53  0  0  1  1  0  0  5  0]
 [ 0  0 53  0  0  0  0  0  1  0]
 [ 0  0  0 52  0  0  0  0  1  1]
 [ 2  0  0  0 57  0  0  0  0  0]
 [ 0  0  0  0  0 47  0  0  2  2]
 [ 0  0  0  0  0  0 47  0  0  0]
 [ 0  0  0  0  0  0  0 48  1  0]
 [ 0  2  0  0  0  0  1  0 50  0]
 [ 0  0  0  0  0  0  0  1  2 51]]


#### Accuracy Score

In [21]:
print(accuracy_score(pre_poly,Y_test))

0.9574074074074074


### Gaussian

In [22]:
gaus = SVC(kernel= "rbf")

In [23]:
gaus.fit(X_train,Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [25]:
pre_gaus = gaus.predict(X_test)

#### Classifiaction Report

In [26]:
print(classification_report(pre_gaus,Y_test))

             precision    recall  f1-score   support

          0       0.39      1.00      0.56        24
          1       0.27      1.00      0.43        15
          2       0.28      1.00      0.44        15
          3       0.67      1.00      0.80        35
          4       0.24      1.00      0.39        14
          5       1.00      0.13      0.23       370
          6       0.65      1.00      0.78        31
          7       0.41      1.00      0.58        20
          8       0.02      1.00      0.03         1
          9       0.28      1.00      0.43        15

avg / total       0.83      0.40      0.35       540



#### Confusion Matrix

In [27]:
print(confusion_matrix(pre_gaus,Y_test))

[[24  0  0  0  0  0  0  0  0  0]
 [ 0 15  0  0  0  0  0  0  0  0]
 [ 0  0 15  0  0  0  0  0  0  0]
 [ 0  0  0 35  0  0  0  0  0  0]
 [ 0  0  0  0 14  0  0  0  0  0]
 [37 40 38 17 44 48 17 29 61 39]
 [ 0  0  0  0  0  0 31  0  0  0]
 [ 0  0  0  0  0  0  0 20  0  0]
 [ 0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0 15]]


#### Accuracy Score

In [28]:
print(accuracy_score(pre_poly,Y_test))

0.9574074074074074


### Sigmoid

In [29]:
sig = SVC(kernel = "sigmoid")

In [30]:
sig.fit(X_train,Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='sigmoid',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [31]:
pre_sig = sig.predict(X_test)

#### Classification Report

In [32]:
print(classification_report(pre_sig,Y_test))

             precision    recall  f1-score   support

          0       0.00      0.00      0.00         0
          1       0.00      0.00      0.00         0
          2       0.00      0.00      0.00         0
          3       0.00      0.00      0.00         0
          4       0.00      0.00      0.00         0
          5       1.00      0.09      0.16       540
          6       0.00      0.00      0.00         0
          7       0.00      0.00      0.00         0
          8       0.00      0.00      0.00         0
          9       0.00      0.00      0.00         0

avg / total       1.00      0.09      0.16       540



C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


#### Confusion Matrix

In [33]:
print(confusion_matrix(pre_sig,Y_test))

[[ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [61 55 53 52 58 48 48 49 62 54]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]]


#### Accuracy score

In [34]:
print(accuracy_score(pre_sig,Y_test))

0.08888888888888889
