In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_digits

In [2]:
data = load_digits()

In [3]:
X= data.data

In [4]:
Y = data.target

In [5]:
from sklearn.preprocessing import StandardScaler

In [6]:
X = StandardScaler().fit_transform(X)

In [7]:
X

array([[ 0.        , -0.33501649, -0.04308102, ..., -1.14664746,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  0.54856067,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  1.56568555,
         1.6951369 , -0.19600752],
       ...,
       [ 0.        , -0.33501649, -0.88456568, ..., -0.12952258,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -0.67419451, ...,  0.8876023 ,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649,  1.00877481, ...,  0.8876023 ,
        -0.26113572, -0.19600752]])

In [8]:
from sklearn.decomposition import PCA

In [9]:
pca = PCA(n_components=35)

In [10]:
X = pca.fit_transform(X)

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size =0.25)

In [12]:
from sklearn.linear_model import LogisticRegression

In [13]:
model = LogisticRegression()

In [14]:
model.fit(X_train,Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [15]:
pre  = model.predict(X_test)

In [16]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [17]:
print(classification_report(pre,Y_test))

             precision    recall  f1-score   support

          0       1.00      0.95      0.98        44
          1       0.98      0.91      0.95        57
          2       1.00      0.96      0.98        51
          3       0.95      1.00      0.98        42
          4       0.96      0.94      0.95        48
          5       0.92      0.96      0.94        46
          6       0.98      0.95      0.96        43
          7       0.95      0.97      0.96        36
          8       0.87      0.93      0.90        43
          9       0.88      0.93      0.90        40

avg / total       0.95      0.95      0.95       450



In [18]:
print(confusion_matrix(pre,Y_test))

[[42  0  0  0  0  1  0  0  0  1]
 [ 0 52  0  0  0  0  0  0  4  1]
 [ 0  0 49  1  0  0  0  0  1  0]
 [ 0  0  0 42  0  0  0  0  0  0]
 [ 0  1  0  0 45  0  1  1  0  0]
 [ 0  0  0  0  0 44  0  0  0  2]
 [ 0  0  0  0  0  1 41  0  1  0]
 [ 0  0  0  0  1  0  0 35  0  0]
 [ 0  0  0  1  1  0  0  0 40  1]
 [ 0  0  0  0  0  2  0  1  0 37]]


In [19]:
print(accuracy_score(pre,Y_test))

0.9488888888888889
