In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/balance-scale/balance-scale.data",header=None)

In [3]:
data.head()

0  1  2  3  4
0  B  1  1  1  1
1  R  1  1  1  2
2  R  1  1  1  3
3  R  1  1  1  4
4  R  1  1  1  5

In [4]:
data.shape

(625, 5)

In [5]:
Y = data.iloc[:,0:1]
X = data.iloc[:,1:5]

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size =0.25)

In [8]:
from sklearn.tree import DecisionTreeClassifier

### Decision tree

#### Gini criterion

In [9]:
classifier = DecisionTreeClassifier(criterion="gini")

In [10]:
classifier.fit(X_train,Y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [11]:
pre = classifier.predict(X_test)

In [12]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [13]:
print(classification_report(pre,Y_test))

             precision    recall  f1-score   support

          B       0.00      0.00      0.00        14
          L       0.86      0.89      0.87        79
          R       0.84      0.83      0.83        64

avg / total       0.78      0.78      0.78       157



In [14]:
print(confusion_matrix(pre,Y_test))

[[ 0  7  7]
 [ 6 70  3]
 [ 7  4 53]]


In [15]:
print(accuracy_score(pre,Y_test))

0.7834394904458599


#### Entropy criterion

In [16]:
classifier2 = DecisionTreeClassifier(criterion="entropy")

In [17]:
classifier2.fit(X_train,Y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [18]:
pre2 = classifier2.predict(X_test)

In [19]:
print(classification_report(pre2,Y_test))

             precision    recall  f1-score   support

          B       0.00      0.00      0.00        12
          L       0.89      0.91      0.90        79
          R       0.90      0.86      0.88        66

avg / total       0.83      0.82      0.82       157



In [20]:
print(confusion_matrix(pre2,Y_test))

[[ 0  7  5]
 [ 6 72  1]
 [ 7  2 57]]


In [21]:
print(accuracy_score(pre2,Y_test))

0.821656050955414


### Random Forest 

#### Gini

In [22]:
from sklearn.ensemble import RandomForestClassifier


In [23]:
classify3 = RandomForestClassifier(criterion="gini",n_jobs=2,random_state=0)

In [24]:
classify3.fit(X_train,Y_train)

C:\Users\Dell\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=2,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [25]:
pre3 = classify3.predict(X_test)

In [26]:
print(classification_report(pre3,Y_test))

             precision    recall  f1-score   support

          B       0.00      0.00      0.00        10
          L       0.91      0.91      0.91        81
          R       0.89      0.85      0.87        66

avg / total       0.85      0.83      0.84       157



In [27]:
print(confusion_matrix(pre3,Y_test))

[[ 0  5  5]
 [ 5 74  2]
 [ 8  2 56]]


In [28]:
print(accuracy_score(pre3,Y_test))

0.8280254777070064


#### Entropy 

In [29]:
classify4 = RandomForestClassifier(criterion="entropy",n_jobs=2,n_estimators=100,random_state=0)

In [30]:
classify4.fit(X_train,Y_train.values.reshape(468,))

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=2,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [31]:
pre4 =classify4.predict(X_test)

In [32]:
print(classification_report(pre4,Y_test))

             precision    recall  f1-score   support

          B       0.00      0.00      0.00         8
          L       0.90      0.90      0.90        81
          R       0.92      0.85      0.89        68

avg / total       0.86      0.83      0.85       157



In [33]:
print(confusion_matrix(pre4,Y_test))

[[ 0  5  3]
 [ 6 73  2]
 [ 7  3 58]]


In [34]:
print(accuracy_score(pre4,Y_test))

0.8343949044585988
