In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
from sklearn import preprocessing
%matplotlib inline

In [2]:
from sklearn.datasets import load_digits

In [3]:
data = load_digits()

In [5]:
x =data.data

In [6]:
y = data.target

In [10]:
X= pd.DataFrame(x)

In [11]:
Y = pd.DataFrame(y)

In [15]:
X.head()

0    1    2     3     4     5    6    7    8    9  ...    54   55   56  \
0  0.0  0.0  5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
1  0.0  0.0  0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
2  0.0  0.0  0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0 ...   5.0  0.0  0.0   
3  0.0  0.0  7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0 ...   9.0  0.0  0.0   
4  0.0  0.0  0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   

    57   58    59    60    61   62   63  
0  0.0  6.0  13.0  10.0   0.0  0.0  0.0  
1  0.0  0.0  11.0  16.0  10.0  0.0  0.0  
2  0.0  0.0   3.0  11.0  16.0  9.0  0.0  
3  0.0  7.0  13.0  13.0   9.0  0.0  0.0  
4  0.0  0.0   2.0  16.0   4.0  0.0  0.0  

[5 rows x 64 columns]

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.3)

In [18]:
from sklearn.linear_model import LogisticRegression

In [19]:
reg =  LogisticRegression()

In [21]:
reg.fit(X_train,Y_train)

C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [22]:
reg.coef_

array([[ 0.00000000e+00, -3.54265287e-02, -3.23350012e-02,
        -1.76974459e-03, -1.11576576e-01, -3.31446173e-01,
        -1.61223681e-01, -1.59648085e-02, -2.18334390e-05,
        -1.34830442e-01,  6.73472442e-02,  1.27452450e-01,
         2.01843661e-01,  2.87375748e-01, -6.44872194e-02,
        -1.65010381e-02, -3.41434843e-04,  6.83241903e-02,
         1.60699359e-01, -1.31879496e-01, -2.57086613e-01,
         3.09841514e-01,  1.72415325e-02, -2.26105603e-03,
        -1.68318500e-04,  7.71920168e-02, -1.67922933e-02,
        -1.94300638e-01, -5.36553525e-01, -3.54820163e-02,
         1.15209979e-01, -3.20173000e-04,  0.00000000e+00,
         3.12521224e-01,  1.83591236e-01, -2.34435743e-01,
        -5.19009600e-01, -1.40845568e-01,  1.75634525e-02,
         0.00000000e+00, -2.08210571e-03, -1.77616984e-02,
         2.56099962e-01, -2.55309397e-01, -2.39677749e-01,
         3.14868092e-02,  1.28489827e-01, -9.28614924e-05,
        -2.69940264e-03, -1.18963930e-01, -1.49744717e-0

In [23]:
reg.intercept_

array([-0.02520877, -1.75866806, -0.03528796, -0.16731943,  0.00537752,
       -0.11203401, -0.04328565, -0.0106698 , -2.26260529, -0.91381675])

In [30]:
pre = reg.predict(X_test)

#### Linear Regression

In [52]:
from sklearn.linear_model import LinearRegression

In [53]:
reg1 = LinearRegression()

In [54]:
reg1.fit(X_train,Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [55]:
pre1 = reg1.predict(X_test)

####  Classification Score

reg.score(X_test,Y_test)

#### Logarthmic loss

In [39]:
from sklearn.model_selection import KFold

In [56]:
from sklearn import model_selection

In [59]:
kfold =model_selection.KFold(n_splits= 10,random_state=7)
res = model_selection.cross_val_score(reg,X,Y,cv= kfold,scoring = "neg_log_loss")

C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for 

In [60]:
res

array([-0.45798961, -0.14435058, -0.61749705, -0.27323142, -0.27594697,
       -0.12815811, -0.11024468, -0.1233365 , -0.62592303, -0.68553964])

#### R2 metrices

In [62]:
res1 = model_selection.cross_val_score(reg1,X,Y,cv= kfold,scoring = "r2")

In [63]:
res1

array([0.40105499, 0.63102463, 0.57072313, 0.59629035, 0.54519634,
       0.67174215, 0.61763556, 0.47611004, 0.4236549 , 0.41044286])

#### mean absolute error

In [64]:
from sklearn.metrics import mean_absolute_error

In [65]:
mean_absolute_error(Y_test,pre1)

1.4337449285128872

#### Mean squared error 

In [66]:
from sklearn.metrics import mean_squared_error

In [68]:
mean_squared_error(Y_test,pre1)

3.5010599721957734

#### Confusion matrix

In [69]:
from sklearn.metrics import confusion_matrix

In [70]:
print(confusion_matrix(Y_test,pre))

[[52  0  0  0  1  0  0  0  0  0]
 [ 0 54  0  2  0  0  0  0  0  1]
 [ 0  0 53  0  0  0  0  0  0  0]
 [ 0  0  0 48  0  1  0  0  1  0]
 [ 0  2  0  0 51  0  0  0  1  0]
 [ 0  0  1  0  0 56  0  0  0  1]
 [ 0  0  0  0  1  1 59  0  0  0]
 [ 0  0  0  0  1  0  0 51  0  0]
 [ 0  4  0  1  0  0  0  0 45  0]
 [ 0  0  0  0  0  1  0  0  2 49]]


#### Classification report

In [71]:
from sklearn.metrics import classification_report

In [73]:
print(classification_report(Y_test,pre))

             precision    recall  f1-score   support

          0       1.00      0.98      0.99        53
          1       0.90      0.95      0.92        57
          2       0.98      1.00      0.99        53
          3       0.94      0.96      0.95        50
          4       0.94      0.94      0.94        54
          5       0.95      0.97      0.96        58
          6       1.00      0.97      0.98        61
          7       1.00      0.98      0.99        52
          8       0.92      0.90      0.91        50
          9       0.96      0.94      0.95        52

avg / total       0.96      0.96      0.96       540

