In [2]:
import numpy as np

## Question 1

In [3]:
a = np.random.random([10,1])

In [4]:
a

array([[0.68167607],
       [0.90815646],
       [0.67724211],
       [0.71294118],
       [0.40442893],
       [0.350172  ],
       [0.90509202],
       [0.40892049],
       [0.24168435],
       [0.62720456]])

In [5]:
np.mean(a)

0.5917518167776448

## Question 2

In [6]:
b= np.random.random([20,1])

In [7]:
b

array([[0.81801909],
       [0.95328914],
       [0.14308963],
       [0.5979051 ],
       [0.78397349],
       [0.70118449],
       [0.65458467],
       [0.74095981],
       [0.45273035],
       [0.39258392],
       [0.50011758],
       [0.2615681 ],
       [0.19406516],
       [0.39553724],
       [0.0396719 ],
       [0.60474023],
       [0.74395279],
       [0.19211772],
       [0.64282431],
       [0.21911494]])

In [8]:
np.var(b)

0.06491018348186786

In [10]:
np.std(b)

0.25477477010463156

## Question 3

In [11]:
x= np.random.random([10,20])

In [12]:
y = np.random.random([20,25])

In [16]:
c = np.dot(x,y)

In [18]:
c

array([[6.82856038, 7.47881772, 7.28799737, 6.63649521, 6.58925119,
        8.01423635, 5.86464253, 6.64777863, 7.22150816, 6.9046932 ,
        6.44474889, 7.03734079, 7.81294924, 6.78609793, 7.16493495,
        6.19520445, 6.7816841 , 6.92167421, 7.60594334, 8.09697996,
        7.33201129, 6.63529882, 6.0786704 , 7.20598887, 5.47580483],
       [5.57302916, 4.90627284, 5.22857338, 4.76455351, 4.28216953,
        6.34230579, 4.24512356, 5.5054312 , 5.52497137, 5.65230577,
        4.59574449, 5.69433831, 5.59897645, 6.16116235, 5.24442959,
        5.02000356, 4.65324559, 5.01689454, 5.72827913, 6.72970905,
        5.5770531 , 4.73662783, 4.04973474, 5.70384694, 3.98836628],
       [6.21114878, 5.88581025, 6.61761401, 5.48975796, 5.31152098,
        7.27309742, 4.78873712, 6.15761642, 6.85506065, 6.95671008,
        6.25133602, 5.69361141, 6.8268119 , 7.71362698, 6.37206287,
        5.48194529, 6.66271846, 5.76726157, 6.85008996, 7.8607155 ,
        7.12000979, 5.15966049, 6.08803743, 6.

In [17]:
c.shape

(10, 25)

In [20]:
np.sum(c)

1385.8514290255723

## Question 4

In [43]:
w = np.arange(10).reshape(10,1)

In [66]:
def myfunc(x,axis):
    return 1/(1+ np.exp(-x))

In [69]:
np.apply_over_axes(myfunc,w,1)

array([[0.5       ],
       [0.73105858],
       [0.88079708],
       [0.95257413],
       [0.98201379],
       [0.99330715],
       [0.99752738],
       [0.99908895],
       [0.99966465],
       [0.99987661]])